log:
  level: INFO

api:
  dashboard: true
  debug: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: https
  https:
    address: ":443"
    http:
      middlewares:
        - default-headers@file
      tls:
        certResolver: domain
        domains:
          - main: saleor.mywheels.com.my
            sans:
              - "*.saleor.mywheels.com.my"
              
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yml
    
certificatesResolvers:
  domain:
    acme:
      email: info@domain.com
      storage: acme.json
      dnsChallenge:
        provider: domain
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"